name: Greeting
on:
  fork:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1>It's great having you contribute to this project</h1> Welcome to the community"
          pr-message: "<h1>It's great having you contribute to this project</h1> Welcome to the community"
          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/85Mch6B9Gw">Discord</a> chat and our <a href="https://github.com/Keribium/">GitHub Organisation</a> - we encourage each other to contribute to open source on their abilities . Let us know about any question.'
