name: linter

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

    - name: Super-Linter
      uses: github/super-linter@v4.10.1
      env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
